# Created with WinGet Releaser using komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: MurkyYT.CSAuto
PackageVersion: 2.1.9
InstallerLocale: en-US
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Valve.Steam
ProductCode: '{F5E4D811-7A92-47F9-BEEC-B6751463D69B}_is1'
ReleaseDate: 2025-06-07
AppsAndFeaturesEntries:
- DisplayName: CSAuto 2.1.9
  ProductCode: '{F5E4D811-7A92-47F9-BEEC-B6751463D69B}_is1'
InstallationMetadata:
  DefaultInstallLocation: '%AppData%\CSAuto'
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/MurkyYT/CSAuto/releases/download/2.1.9/CSAuto_Installer.exe
  InstallerSha256: AEE3F94FC92C7F54F1FEDF639441CA2524D1550C31390BE00B47DCD1F10B72DB
ManifestType: installer
ManifestVersion: 1.9.0
