# Created with WinGet Releaser using komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: MurkyYT.CSAuto
PackageVersion: 2.1.7
InstallerLocale: en-US
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Valve.Steam
ProductCode: '{F5E4D811-7A92-47F9-BEEC-B6751463D69B}_is1'
ReleaseDate: 2025-06-07
AppsAndFeaturesEntries:
- DisplayName: CSAuto 2.1.7
  ProductCode: '{F5E4D811-7A92-47F9-BEEC-B6751463D69B}_is1'
InstallationMetadata:
  DefaultInstallLocation: '%AppData%\CSAuto'
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/MurkyYT/CSAuto/releases/download/2.1.7/CSAuto_Installer.exe
  InstallerSha256: 1CAA00B19D95E6020D044DDA9993CA6A83B7A20F4B6E86A509CCC1B2C550C51A
ManifestType: installer
ManifestVersion: 1.9.0
