# Created with WinGet Releaser using komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: MurkyYT.CSAuto
PackageVersion: 2.1.8
InstallerLocale: en-US
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Valve.Steam
ProductCode: '{F5E4D811-7A92-47F9-BEEC-B6751463D69B}_is1'
ReleaseDate: 2025-06-07
AppsAndFeaturesEntries:
- DisplayName: CSAuto 2.1.8
  ProductCode: '{F5E4D811-7A92-47F9-BEEC-B6751463D69B}_is1'
InstallationMetadata:
  DefaultInstallLocation: '%AppData%\CSAuto'
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/MurkyYT/CSAuto/releases/download/2.1.8/CSAuto_Installer.exe
  InstallerSha256: 84D3035A6AA3E9CA1C7D6EB59B20FCC58724BB0F948D06A189E2B270B97FA6CC
ManifestType: installer
ManifestVersion: 1.9.0
